import { Activity, ArrowRight, Building2, ChartNoAxesCombined, CircleAlert, Clock3, Globe2, Layers3, Link2, Newspaper, ShieldAlert } from "lucide-react";
import { PageHeader, SectionHeader, Tag } from "@/components/ui";
import { fusionDemo, type FusionEngine } from "@/data/demo/fusion";

const tone = (state: string) => state === "Supportive" ? "bullish" : state === "Adverse" ? "bearish" : state === "Insufficient" ? "blocked" : "neutral";
const engineIcons = { TECH: ChartNoAxesCombined, HIST: Clock3, NEWS: Newspaper, MACRO: Globe2, FUND: Building2, PSYCH: Activity, FLOW: Layers3 } satisfies Record<FusionEngine["short"], typeof Activity>;

function EngineRecord({ engine, index }: { engine: FusionEngine; index: number }) {
  const Icon = engineIcons[engine.short];
  return <article className={`fusion-engine ${engine.orientation.toLowerCase()}`} style={{ "--delay": `${index * 55}ms` } as React.CSSProperties}>
    <div className="engine-code"><Icon size={16} aria-hidden="true" /><span>{engine.short}</span></div>
    <div className="engine-copy"><strong>{engine.name}</strong><span>{engine.evidence}</span>
      <dl className="engine-measures"><div><dt>Quality</dt><dd>{engine.quality}</dd></div><div><dt>Evidence certainty</dt><dd>{engine.evidenceCertainty}</dd></div><div><dt>Freshness</dt><dd>{engine.freshness}</dd></div></dl>
      <details className="engine-inspect"><summary>Inspect evidence</summary><p>{engine.status} · {engine.validation} · observation {engine.source}</p></details>
    </div>
    <div className="engine-status"><Tag tone={tone(engine.orientation)}>{engine.orientation}</Tag></div>
    <i className="fusion-trace" aria-hidden="true" style={{ "--independence": engine.independence } as React.CSSProperties} />
  </article>;
}

export default function FusionPage() { return <><PageHeader title="Evidence fusion">Seven specialist systems, one explainable evidence state. Agreement is not probability.</PageHeader><div className="content fusion-page">
  <section className="fusion-thesis panel" aria-labelledby="fusion-state-title"><div className="fusion-verdict"><div className="fusion-meta"><Tag>Demo / engineering evidence</Tag><span className="stamp">V0 · CUTOFF ALIGNED</span></div><h2 id="fusion-state-title">The evidence is conflicted.</h2><p>Supportive technical and fundamental evidence meets adverse macro conditions and crowded psychology. Positioning is unavailable, so the system abstains from a predictive conclusion.</p><div className="fusion-facts" aria-label="Fusion summary"><div><span>Agreement</span><strong>{fusionDemo.agreement}</strong></div><div><span>Uncertainty</span><strong>{fusionDemo.uncertainty}</strong></div><div><span>Coverage</span><strong>{fusionDemo.coverage}</strong></div><div><span>Decision</span><strong>ABSTAIN</strong></div></div></div>
    <div className="fusion-field" aria-label="Seven specialist engine convergence"><div className="fusion-engine-list"><h3>Specialist evidence</h3>{fusionDemo.engines.map((engine, index) => <EngineRecord engine={engine} index={index} key={engine.name} />)}</div><div className="fusion-core"><span>Evidence state</span><strong>{fusionDemo.state}</strong><span>Prediction state</span><b>ABSTAIN</b><small>The systems disagree and positioning coverage is incomplete, so no predictive conclusion is produced.</small></div></div>
  </section>
  <section className="section"><SectionHeader title="Where the systems disagree" note="Contradictions remain unresolved, not averaged away" /><div className="fusion-conflicts">{fusionDemo.contradictions.map(item => { const [left, right] = item.pair.split(" × "); return <article className="conflict-record" key={item.pair}><div className="conflict-pair"><ShieldAlert size={18} aria-hidden="true" /><strong>{left}</strong><span>vs</span><strong>{right}</strong></div><Tag tone={item.severity === "High" ? "bearish" : "demo"}>{item.severity} severity</Tag><p>{item.reason}</p></article>; })}</div></section>
  <section className="section"><SectionHeader title="Contribution ledger" note="Quality and independence precede engine count" /><div className="ledger panel"><div><h3>What supports the state</h3>{fusionDemo.supports.map(x => <p key={x}><ArrowRight size={13} aria-hidden="true" />{x}</p>)}</div><div><h3>What opposes it</h3>{fusionDemo.opposes.map(x => <p key={x}><CircleAlert size={13} aria-hidden="true" />{x}</p>)}</div><div><h3>Dependency warnings</h3><p><Link2 size={13} aria-hidden="true" />News and Psychology partly rely on the same underlying event, so they are not counted as fully independent evidence.</p><p><Link2 size={13} aria-hidden="true" />Technical and Historical partly rely on the same price-derived features, so their agreement is discounted.</p><details className="dependency-detail"><summary>Inspect dependency factors</summary><p>Psychology independence: 0.35 · News independence: 0.65 · Historical independence: 0.65</p></details></div></div></section>
  <details className="fusion-provenance panel"><summary>Inspect evidence provenance <ArrowRight size={14} aria-hidden="true" /></summary><div className="provenance-detail"><h2>Snapshot → contribution → observation</h2><dl><div><dt>Snapshot</dt><dd>{fusionDemo.snapshotId}</dd></div><div><dt>Cutoff</dt><dd>{fusionDemo.cutoff}</dd></div><div><dt>Validation</dt><dd>Engineering only · not predictively validated</dd></div><div><dt>Contribution chain</dt><dd>Quality → freshness → dependency discount → contradiction check → abstention</dd></div><div><dt>Observations</dt><dd>{fusionDemo.engines.map(engine => engine.source).join(" · ")}</dd></div><div><dt>Specialist snapshots</dt><dd>{fusionDemo.engines.map(engine => `${engine.short}-${engine.snapshotHash}`).join(" · ")}</dd></div></dl></div></details>
  <section className="section fusion-change"><div><h2>What would change the view</h2><p>Evidence-state conditions, not trade triggers.</p></div><ol>{fusionDemo.changes.map(item => <li key={item.engine}><span>{item.engine}</span>{item.condition}</li>)}</ol></section>
  <p className="fusion-disclaimer">DEMO / ENGINEERING EVIDENCE · SYNTHETIC SPECIALIST OUTPUTS · NOT A LIVE PREDICTION · NO RETURN PROBABILITY</p>
</div></>; }
