packages:
  - apps/*

overrides:
  '@vercel/backends>path-to-regexp': 8.4.0
  '@vercel/express>path-to-regexp': 8.4.0
  '@vercel/fun>@tootallnate/once': 2.0.1
  '@vercel/fun>path-to-regexp': 8.4.0
  '@vercel/fun>tar': 7.5.22
  '@vercel/hono>path-to-regexp': 8.4.0
  '@vercel/node>path-to-regexp': 6.3.0
  '@vercel/node>undici': 6.28.1
  '@vercel/python-analysis>js-yaml': 4.3.2
  '@vercel/python-analysis>minimatch': 10.2.6
  '@vercel/python-analysis>smol-toml': 1.6.1
  '@vercel/remix-builder>path-to-regexp': 6.3.0
  '@vercel/rust>smol-toml': 1.6.1
  '@vercel/static-config>ajv': 8.18.0
  'vercel>smol-toml': 1.6.1
  'vercel>undici': 6.28.1

allowBuilds:
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - unrs-resolver
